import { TERRAIN_SHADER } from "./terrain-shaders.js";

// Systems Cube deliberately shares the proven relief-to-canonical-QR shader.
// Its distinctive deterministic geometry is generated by createSeedBlockField.
export const SYSTEMS_CUBE_SHADER = TERRAIN_SHADER;
